# Generated by Django 3.0.5 on 2020-05-30 14:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telephone')),
                ('total_order_count', models.IntegerField(default=0, verbose_name='Total order count')),
                ('first_purchased', models.DateTimeField(null=True, verbose_name='First purchased date')),
                ('last_purchased', models.DateTimeField(null=True, verbose_name='Last purchased date')),
                ('max_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Max price')),
                ('total_selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Total selling price')),
                ('average_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Average price')),
                ('mileage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='Mileage')),
                ('memo', models.TextField(blank=True, verbose_name='User memo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
