# Generated by Django 3.0.7 on 2020-06-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubOrderListMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Club', verbose_name='Golf club')),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order', verbose_name='Order list')),
            ],
            options={
                'verbose_name': 'Golf club order list membership',
                'verbose_name_plural': 'Golf club order list membership',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='clubs',
            field=models.ManyToManyField(through='booking.ClubOrderListMembership', to='booking.Club'),
        ),
    ]
