# Generated by Django 3.0.7 on 2020-06-12 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_method', models.IntegerField(choices=[(0, 'Credit Card'), (1, 'Bank Transfer'), (2, 'PayPal')], db_index=True, default=0, verbose_name='Payment method')),
                ('category', models.IntegerField(choices=[(0, 'Credit Card'), (1, 'Bank Transfer'), (2, 'PayPal')], db_index=True, default=0, verbose_name='Transaction category')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Amount')),
                ('received', models.DateTimeField(verbose_name='received date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order transaction',
                'verbose_name_plural': 'Order transactions',
            },
        ),
    ]
