# Generated by Django 3.0.7 on 2020-06-13 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubOrderChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Booking opened'), (1, 'Booking pending'), (2, 'Booking offered'), (3, 'Payment completed'), (4, 'Booking confirmed'), (5, 'Booking unavailable'), (6, 'Payment adjustment'), (7, 'Payment adjusted'), (8, 'Refund requested'), (9, 'Refund pending'), (10, 'Refunded'), (11, 'Refunded'), (12, 'Voided')], db_index=True, default=0, verbose_name='Order status')),
                ('total_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Total selling price')),
                ('total_cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Total cost price')),
                ('round_date', models.DateField(db_index=True, verbose_name='Round date')),
                ('round_time', models.TimeField(db_index=True, verbose_name='Round time')),
                ('pax', models.IntegerField(default=4, verbose_name='PAX')),
                ('green_fee_selling_price', models.DecimalField(decimal_places=0, default=0, help_text='THB', max_digits=11, verbose_name='Green fee selling price')),
                ('green_fee_cost_price', models.DecimalField(decimal_places=0, default=0, help_text='THB', max_digits=11, verbose_name='Green fee cost price')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Club', verbose_name='Golf club')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order', verbose_name='Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
