# Generated by Django 3.0.7 on 2020-06-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluborderlistmembership',
            name='order_list',
        ),
        migrations.AddField(
            model_name='cluborderlistmembership',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.Order', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
