# Generated by Django 3.0.7 on 2020-06-13 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category', models.IntegerField(choices=[(0, 'Payment'), (1, 'Refund'), (2, 'Purchase')], db_index=True, default=0, verbose_name='Transaction category')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Amount')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Asset', verbose_name='Asset')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order sales transaction',
                'verbose_name_plural': 'Order sales transactions',
            },
        ),
        migrations.DeleteModel(
            name='OrderSales',
        ),
    ]
