# Generated by Django 3.0.7 on 2020-06-13 17:55

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cluborderchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluborderchangelog',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='cluborderchangelog',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
