# Generated by Django 3.0.7 on 2020-06-11 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200611_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluborderlistmembership',
            name='position',
        ),
        migrations.AddField(
            model_name='cluborderlistmembership',
            name='green_fee_cost_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='THB', max_digits=11, verbose_name='Green fee cost price'),
        ),
        migrations.AddField(
            model_name='cluborderlistmembership',
            name='green_fee_selling_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='THB', max_digits=11, verbose_name='Green fee selling price'),
        ),
        migrations.AddField(
            model_name='cluborderlistmembership',
            name='pax',
            field=models.IntegerField(default=4, verbose_name='PAX'),
        ),
        migrations.AddField(
            model_name='cluborderlistmembership',
            name='round_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Round date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluborderlistmembership',
            name='round_time',
            field=models.TimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Round time'),
            preserve_default=False,
        ),
    ]
