# Generated by Django 3.0.7 on 2020-06-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_asset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTransaction',
            new_name='OrderSales',
        ),
        migrations.AlterModelOptions(
            name='ordersales',
            options={'verbose_name': 'Order sales transaction', 'verbose_name_plural': 'Order sales transactions'},
        ),
    ]
