# Generated by Django 3.0.7 on 2020-06-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200618_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, verbose_name='Booking message'),
        ),
    ]
