# Generated by Django 3.0.7 on 2020-06-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.IntegerField(choices=[(0, 'GB prime pay'), (1, 'Petty cash'), (2, 'Passbook Krungsri'), (3, 'Passbook Kasikorn')], db_index=True, default=0, verbose_name='Asset code'),
        ),
    ]
