# Generated by Django 3.0.7 on 2020-06-12 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200613_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='received',
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction date'),
            preserve_default=False,
        ),
    ]
