# Generated by Django 3.0.7 on 2020-06-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200613_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettransaction',
            options={'verbose_name': 'Asset transaction', 'verbose_name_plural': 'Asset transactions'},
        ),
    ]
