# Generated by Django 3.0.7 on 2020-06-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200614_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluborderchangelog',
            options={'verbose_name': 'Golf club order changelog', 'verbose_name_plural': 'Golf club order changelog'},
        ),
    ]
