# Generated by Django 3.0.5 on 2020-05-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Rate',
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Service rate', 'verbose_name_plural': 'Service rates'},
        ),
    ]
