# Generated by Django 3.0.5 on 2020-05-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='weekdays_max_in_advance',
            field=models.IntegerField(db_index=True, default=30, verbose_name='Weekdays maximum in advance'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekdays_min_in_advance',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Weekdays minimum in advance'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekend_max_in_advance',
            field=models.IntegerField(db_index=True, default=7, verbose_name='Weekend maximum in advance'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekend_min_in_advance',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Weekend minimum in advance'),
        ),
    ]
