# Generated by Django 3.0.5 on 2020-05-15 03:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='club',
            name='caddie_fee_selling_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='THB', max_digits=11, verbose_name='Caddie fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='cart_fee_selling_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='THB', max_digits=11, verbose_name='Cart fee'),
            preserve_default=False,
        ),
    ]
