# Generated by Django 3.0.5 on 2020-05-25 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Club list title')),
                ('code', models.CharField(max_length=255, verbose_name='Club list code')),
            ],
            options={
                'verbose_name': 'Golf club list',
                'verbose_name_plural': 'Golf club lists',
            },
        ),
        migrations.CreateModel(
            name='ClubListMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='position')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.Club', verbose_name='Golf club')),
                ('club_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.ClubList', verbose_name='Golf club list')),
            ],
            options={
                'verbose_name': 'Golf club list membership',
                'verbose_name_plural': 'Golf club list membership',
            },
        ),
        migrations.AddField(
            model_name='clublist',
            name='products',
            field=models.ManyToManyField(through='golf.ClubListMembership', to='golf.Club'),
        ),
    ]
