# Generated by Django 3.0.5 on 2020-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Rate title'),
            preserve_default=False,
        ),
    ]
