# Generated by Django 3.0.5 on 2020-05-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='title_enlish',
            new_name='title_english',
        ),
    ]
