# Generated by Django 3.0.5 on 2020-05-27 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('order_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Order no')),
                ('fullname', models.CharField(blank=True, max_length=64, verbose_name='Personal name')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-agent')),
                ('accept_language', models.TextField(blank=True, verbose_name='Accept-language')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('payment_method', models.IntegerField(choices=[(0, 'Credit Card'), (1, 'Bank Transfer'), (2, 'PayPal')], db_index=True, default=1, verbose_name='Payment method')),
                ('transaction_id', models.CharField(blank=True, max_length=64, verbose_name='Transaction id')),
                ('status', models.IntegerField(choices=[(0, 'Booking opened'), (1, 'Booking pending'), (2, 'Booking offered'), (3, 'Payment completed'), (4, 'Booking confirmed'), (5, 'Booking unavailable'), (6, 'Payment adjustment'), (7, 'Payment adjusted'), (8, 'refund requested'), (9, 'refund pending'), (10, 'refunded'), (11, 'refunded'), (12, 'Voided')], db_index=True, default=0, verbose_name='Order status')),
                ('total_selling_price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Total selling price')),
                ('total_cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Total cost price')),
                ('message', models.TextField(blank=True, verbose_name='Order message')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf.Order', verbose_name='Parent order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Booking order',
                'verbose_name_plural': 'Booking orders',
            },
        ),
        migrations.DeleteModel(
            name='ClubBooking',
        ),
    ]
