# Generated by Django 3.0.5 on 2020-05-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='title',
            field=models.IntegerField(choices=[(0, 'Day golf'), (1, 'Day golf 1st round'), (2, 'Day golf 2nd round'), (3, 'Twilight golf'), (4, 'Night golf')], db_index=True, default=0, verbose_name='Rate title'),
        ),
    ]
