# Generated by Django 3.0.7 on 2020-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='max_pax',
            field=models.IntegerField(default=4, verbose_name='Max PAX'),
        ),
    ]
