# Generated by Django 3.0.5 on 2020-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='green_fee_selling_price',
            field=models.DecimalField(db_index=True, decimal_places=2, help_text='THB', max_digits=11, verbose_name='Start from'),
        ),
        migrations.AlterField(
            model_name='club',
            name='position',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title_english',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Golf club English name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title_korean',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Golf club Korean name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title_thai',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Golf club Thai name'),
        ),
    ]
