# Generated by Django 3.0.5 on 2020-05-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='area',
        ),
        migrations.RemoveField(
            model_name='club',
            name='province',
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.Province', verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='golf.Area', verbose_name='Location area'),
            preserve_default=False,
        ),
    ]
