# Generated by Django 3.0.5 on 2020-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='green_fee_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='THB', max_digits=11, verbose_name='Start from'),
            preserve_default=False,
        ),
    ]
