# Generated by Django 3.0.5 on 2020-05-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='club',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Longitude'),
        ),
    ]
