# Generated by Django 3.0.5 on 2020-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
