# Generated by Django 3.0.5 on 2020-05-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_price_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='slot_end',
            field=models.TimeField(verbose_name='Slot end time'),
        ),
        migrations.AlterField(
            model_name='price',
            name='slot_start',
            field=models.TimeField(verbose_name='Slot start time'),
        ),
    ]
