# Generated by Django 3.0.5 on 2020-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200528_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(0, 'Credit Card'), (1, 'Bank Transfer'), (2, 'PayPal')], db_index=True, default=0, verbose_name='Payment method'),
        ),
    ]
