# Generated by Django 3.0.5 on 2020-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200521_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cart_required',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Require golf cart'),
        ),
    ]
