# Generated by Django 3.0.5 on 2020-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200515_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Golf club address'),
        ),
    ]
