# Generated by Django 3.0.5 on 2020-05-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200525_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clublist',
            old_name='products',
            new_name='clubs',
        ),
    ]
