# Generated by Django 3.0.5 on 2020-05-02 13:38

from django.db import migrations, models
import easy_thumbnails.fields
import golf.models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='club',
            name='thumbnail1',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=golf.models.upload_directory_path, verbose_name='Thumbnail 1'),
        ),
        migrations.AddField(
            model_name='club',
            name='thumbnail2',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=golf.models.upload_directory_path, verbose_name='Thumbnail 2'),
        ),
        migrations.AddField(
            model_name='club',
            name='thumbnail3',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=golf.models.upload_directory_path, verbose_name='Thumbnail 3'),
        ),
        migrations.AddField(
            model_name='club',
            name='thumbnail4',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=golf.models.upload_directory_path, verbose_name='Thumbnail 4'),
        ),
        migrations.AddField(
            model_name='club',
            name='thumbnail5',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=golf.models.upload_directory_path, verbose_name='Thumbnail 5'),
        ),
    ]
