# Generated by Django 3.0.5 on 2020-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20200508_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', help_text='A short label containing only letters, numbers, underscores or hyphens for URL', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
