# Generated by Django 3.0.5 on 2020-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_club_cart_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.IntegerField(choices=[(0, 'Club open'), (1, 'Club closed')], db_index=True, default=0, verbose_name='Club status'),
        ),
    ]
