# Generated by Django 3.0.5 on 2020-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_club_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone number'),
        ),
    ]
